/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.ac by autoheader.  */

/* Define to 1 if you have the `cpputil' library (-lcpputil). */
#define HAVE_LIBCPPUTIL 1

/* Name of package */
#define PACKAGE "hrcs_lab"

/* Define to the address where bug reports for this package should be sent. */
#define PACKAGE_BUGREPORT "pratzlaff@cfa.harvard.edu"

/* Define to the full name of this package. */
#define PACKAGE_NAME "hrcs_lab"

/* Define to the full name and version of this package. */
#define PACKAGE_STRING "hrcs_lab 0.1"

/* Define to the one symbol short name of this package. */
#define PACKAGE_TARNAME "hrcs_lab"

/* Define to the version of this package. */
#define PACKAGE_VERSION "0.1"

/* Version number of package */
#define VERSION "0.1"
